#pragma config(Motor,  port1,           leftMotor,     tmotorNone, openLoop)
#pragma config(Motor,  port6,           clawMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port10,          rightMotor,    tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Avoid editing these pragma statements directly. Use "Motor and Sensor Setup" instead.
//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
//This macro is equivalent to Java's length() function. Divide the digital size (in bytes) of an
//array by the digital size of one of its elements to get the number of elements in the array
#define ARRAYSIZE(a) sizeof(a)/sizeof(a[0])
//ADD NEW SPEEDS BETWEEN CURLY BRACES BELOW, ORDERED BY MAGNITUDE
const float speeds[] = {0.6,1.5};
byte gear = 0;

task main()
{
	while(true)
	{
		/*Motor control
		*The power given to the motor is determined by the chosen value in the array speeds[].
		*/
		motor[leftMotor] = vexRT[Ch3]*speeds[gear];
		motor[rightMotor] = vexRT[Ch2]*speeds[gear];
		/*Arm control
		*If button 6 is pressed, the arm goes up or down depending on if it is
		*button 6U or button 6D, respectively. Otherwise, the motor doesn't run.
		*/
		if(vexRT[Btn6U] == 1)
		{
			motor[armMotor] = 40;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[armMotor] = -40;
		}
		else
		{
			motor[armMotor] = 0;
		}
		/*Claw control
		*If button 5 is pressed, the claw motor opens or closes depending on if it is
		*button 5U or button 5D. Otherwise, the motor doesn't run.
		*/
		if(vexRT[Btn5U]==1)
		{
			motor[clawMotor] = 40;
		}
		else if(vexRT[Btn5D]==1)
		{
			motor[clawMotor] = -40;
		}
		else
		{
			motor[clawMotor] = 0;
		}

		/*Gear control
		*This part of the program changes the speed of the robot. The int variable isHigherGear only ever has
		*a value of 0 or 1 (true or false). 0 is the lower gear and 1 is the higher. These if statements
		*change the gear between the two when button 8R is pressed. See void function changeGear().
		*/
		if(vexRT[Btn8U] == 1 && gear++ < ARRAYSIZE(speeds))
			gear++;
		if(vexRT[Btn8D] == 1 && gear-- > 0)
			gear--;
	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
