#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port6,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Avoid editing these pragma statements directly. Use "Motor and Sensor Setup" instead

/*----------------------------------------------------------------------------------------------------*\
|*                           - Dual Joystick Control with Arm - 1 Remote -                            *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses both the Left and the Right joysticks to run the robot using "tank control".    *|
|*  The Group 6 buttons on the top-right of the VEXnet Joystick are used to raise and lower an arm.   *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    2)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Motor - Port 2          rightMotor           VEX Motor           Right motor                    *|
|*    Motor - Port 3          leftMotor            VEX Motor           Left motor                     *|
|*    Motor - Port 6          armMotor             VEX Motor           Arm motor                      *|
\*----------------------------------------------------------------------------------------------------*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
int higherGear = 0;
int higherSpeed = 1.5;
int lowerSpeed = 0.5;

void changeGear()
{
	if(higherGear == 0)
	{
		higherGear = 1;
	}
	else if(higherGear == 1)
	{
		higherGear = 0;
	}
}

task main()
{
	while(true)
	{
		/*Motor control
		*This robot was slightly unbalanced between the two sides, which is why the motor statements have different
		*multipliers.
		*
		*The if statements check the value of higherGear before sending instructions to the motors. If higherGear
		*is 1, the motors receive a higher multiplier (1.7 and 1.5). If higherGear is 0, the motors receive the
		*lower multipliers (0.55 and 0.5).
		*/
		if(higherGear == 1)
		{
			motor[leftMotor] = vexRT[Ch3]*higherSpeed*1.1;
			motor[rightMotor] = vexRT[Ch2]*higherSpeed;
		}
		else if(higherGear == 0)
		{
			motor[leftMotor] = vexRT[Ch3]*lowerSpeed*1.1;
			motor[rightMotor] = vexRT[Ch2]*lowerSpeed;
		}

		/*Arm control
		*If button 6 is pressed, the arm goes up or down depending on if it is
		*button 6U or button 6D, respectively. Otherwise, the motor doesn't run.
		*/
		if(vexRT[Btn6U] == 1)
		{
			motor[armMotor] = 40;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[armMotor] = -40;
		}
		else
		{
			motor[armMotor] = 0;
		}

		/*Claw control
		*If button 5 is pressed, the claw motor opens or closes depending on if it is
		*button 5U or button 5D. Otherwise, the motor doesn't run.
		*/
		if(vexRT[Btn5U] == 1)
		{
			motor[clawMotor] = 60;
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor[clawMotor] = -60;
		}
		else
		{
			motor[clawMotor] = 0;
		}

		/*Gear control
		*This part of the program changes the speed setting of the robot. The int variable higherGear only ever has
		*a value of 0 or 1. 0 is the lower gear and 1 is the higher. These if statements change the gear between
		*the two when button 8R is pressed. See void function changeGear().
		*/
		if(vexRT[Btn8R] == 1)
		{
			changeGear();
		}
	}
}
