#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port6,           clawMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Avoid editing these pragma statements directly. Use "Motor and Sensor Setup" instead.

//This macro is equivalent to Java's length() function. Divide the digital size (in bytes) of an
//array by the digital size of one of its elements to get the number of elements in the array.
#define ARRAYSIZE(a) sizeof(a)/sizeof(a[0])

//ADD NEW SPEEDS BETWEEN CURLY BRACES BELOW, ORDERED BY MAGNITUDE
//(Remember array indices start at 0; the first item in speeds is speeds[0], not speeds[1])
const float speeds[] = {0.6,1.5,3.0};

//This variable defines which element in array speeds[] is selected. See "Motor control" below.
//The value given to gear is which gear it is switched to first
byte gear = 1;

task main()
{
	while(true)
	{
		/* MOTOR CONTROL
		 * The power given to the motor is determined by the chosen value in the array speeds[] times the amount of force on
		 * the joystick.
		 */
		motor[leftMotor] = vexRT[Ch3]*speeds[gear];
		motor[rightMotor] = vexRT[Ch2]*speeds[gear];

		/* ARM CONTROL
		 * If button 6 is pressed, the arm goes up or down depending on if it is
		 * button 6U or button 6D, respectively. Otherwise, the motor doesn't run.
		 */
		if(vexRT[Btn6U] == 1)
		{
			motor[armMotor] = 40;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[armMotor] = -40;
		}
		else
		{
			motor[armMotor] = -10;
		}

		/* CLAW CONTROL
		 * If button 5 is pressed, the claw motor opens or closes depending on if it is
		 * button 5U or button 5D. Otherwise, the motor doesn't run.
		 */
		if(vexRT[Btn5U]==1)
		{
			motor[clawMotor] = 40;
		}
		else if(vexRT[Btn5D]==1)
		{
			motor[clawMotor] = -40;
		}
		else
		{
			motor[clawMotor] = 0;
		}

		/* GEAR CONTROL
		 * This part of the program changes the speed of the robot. When the button 8U is pressed, the program tests whether
		 * the next gear is equal to the length of array speeds[]. If so, you cant increment gear.
		 */
		if(vexRT[Btn8U] == 1 && gear < ARRAYSIZE(speeds) - 1) { // If gear is less than maximum index in speeds
			++gear;
			sleep(100);
		}
		if(vexRT[Btn8D] == 1 && gear > 0) {
			--gear;
			sleep(100);
		}
	}
}
